matches:
  # Simple text replacement
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: "m15z"
    replace: "materialization"
  - trigger: "m11z"
    replace: "materialize"
  - trigger: "status@@"
    replace: "bin/semanticq control status --sections snapshot_creation"
  - trigger: "e@@"
    replace: "{{email}}"
    vars:
      - name: email
        type: shell
        params:
          cmd: op item get 'Ryan Crumley' --fields email

