matches:
  # Simple text replacement
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: "m15z"
    replace: "materialization"
  - trigger: "m11z"
    replace: "materialize"
  - trigger: "@@"
    replace: "crumley@gmail.com"