matches:
  # Simple text replacement
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: "m15z"
    replace: "materialization"
  - trigger: "m11z"
    replace: "materialize"
  - trigger: "@@"
    replace: "{{email}}"
    vars:
      - name: email
        type: shell
        params:
          cmd: "if [ \"$PROFILE_TYPE\" = 'work' ]; then op item get 'Ryan Crumley' --fields email; else op item get 'Ryan Crumley' --fields email; fi"