#!/usr/bin/env bash
#
# End-to-end tests for install.sh.
#
# Every test runs against a throwaway home under $TMPDIR. Nothing here touches
# the real $HOME -- that is what DOTFILES_TARGET is for, and it is why the
# installer suppresses every machine-level step (Homebrew, macOS defaults,
# agent skills) as soon as the target is not your home directory.
#
#   ./test/install-test.sh
#
# Exit status is 0 only if every check passed.

set -uo pipefail

REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
PASS=0
FAIL=0
HOMES=""

ok()    { PASS=$((PASS + 1)); printf '  ok   %s\n' "$1"; }
bad()   { FAIL=$((FAIL + 1)); printf '  FAIL %s\n' "$1"; }
group() { printf '\n%s\n' "$1"; }

# assert "description" cmd...   -- passes when cmd succeeds
# refute "description" cmd...   -- passes when cmd fails
assert() { local d=$1; shift; if "$@"; then ok "$d"; else bad "$d"; fi; }
refute() { local d=$1; shift; if "$@"; then bad "$d"; else ok "$d"; fi; }

real_dir()   { [ -d "$1" ] && [ ! -L "$1" ]; }
relative_link() { local t; t=$(readlink "$1") && case "$t" in /*) return 1 ;; *) return 0 ;; esac; }
same()       { [ "$1" = "$2" ]; }
grep_out()   { printf '%s' "$2" | grep -q -- "$1"; }
entry_count() { [ "$(find "$1" ! -type d | wc -l | tr -d ' ')" = "$2" ]; }

newhome() {
  local d
  d=$(mktemp -d "${TMPDIR:-/tmp}/dotfiles-test.XXXXXX")
  HOMES="$HOMES $d"
  printf '%s\n' "$d"
}

cleanup() {
  local d
  for d in $HOMES; do
    case "$d" in
      "$HOME"|"$HOME"/*|/|'') printf 'refusing to clean %s\n' "$d" >&2 ;;
      *) rm -rf "$d" ;;
    esac
  done
}
trap cleanup EXIT

# mode, size, mtime -- BSD and GNU stat spell this differently.
statline() {
  if stat -c '%a %s %Y' "$1" >/dev/null 2>&1; then
    stat -c '%a %s %Y' "$1"
  else
    stat -f '%Lp %z %m' "$1"
  fi
}

# A fingerprint of a tree, used to prove that a run changed nothing.
snapshot() {
  local root=$1 p
  find "$root" -mindepth 1 | sort | while IFS= read -r p; do
    printf '%s|%s|%s\n' "$(statline "$p")" "$(readlink "$p" 2>/dev/null || printf -- '-')" "${p#"$root"}"
  done
}

install_into() {
  local target=$1
  shift
  DOTFILES_TARGET="$target" "$REPO/install.sh" "$@"
}

# Same, with all output swallowed: used when only the exit status matters.
install_quietly() {
  install_into "$@" >/dev/null 2>&1
}

install_linux() {
  local target=$1
  shift
  DOTFILES_PLATFORM=linux DOTFILES_TARGET="$target" "$REPO/install.sh" "$@" >/dev/null 2>&1
}

shellcheck_all() {
  (cd "$REPO" && shellcheck -x install.sh upgrade.sh macos/defaults.sh \
      lib/common.sh lib/packages.sh lib/stow.sh test/install-test.sh)
}

# ---------------------------------------------------------------------------

group "Guardrails"
assert "the real HOME is never the target" [ -z "${DOTFILES_TARGET:-}" ]

group "Package discovery and the platform map"
darwin_list=$(DOTFILES_PLATFORM=darwin "$REPO/install.sh" --list)
linux_list=$(DOTFILES_PLATFORM=linux "$REPO/install.sh" --list)
assert "starship is discovered (the old hardcoded list missed it)" grep_out '^starship$' "$darwin_list"
assert "macOS keeps hammerspoon" grep_out '^hammerspoon$' "$darwin_list"
refute "Linux skips hammerspoon" grep_out '^hammerspoon$' "$linux_list"
refute "Linux skips karabiner"   grep_out '^karabiner$' "$linux_list"
refute "Linux skips espanso"     grep_out '^espanso$' "$linux_list"
refute "Linux skips ghostty"     grep_out '^ghostty$' "$linux_list"
assert "Linux still gets fish"   grep_out '^fish$' "$linux_list"

group "Clean install"
h1=$(newhome)
assert "install exits 0" install_into "$h1" -q
assert "the atuin config is a symlink" [ -L "$h1/.config/atuin/config.toml" ]
assert "starship is linked" [ -L "$h1/.config/starship.toml" ]
assert "links are relative, so stow owns them" relative_link "$h1/.config/atuin/config.toml"
assert "--no-folding: ~/.config is a real directory, not a link into the repo" real_dir "$h1/.config"

group "Idempotency"
before=$(snapshot "$h1")
assert "second run exits 0" install_into "$h1" -q
assert "second run leaves the tree byte-identical" same "$before" "$(snapshot "$h1")"

group "Conflicts are refused by default"
h2=$(newhome)
install_into "$h2" -q
rm "$h2/.config/atuin/config.toml"
printf '## generated by atuin\n' >"$h2/.config/atuin/config.toml"          # (a) plain file
rm "$h2/.ripgreprc"; mkdir "$h2/.ripgreprc"; touch "$h2/.ripgreprc/junk"   # (b) directory
rm "$h2/.gitconfig"; ln -s /etc/hosts "$h2/.gitconfig"                     # (c) foreign symlink
rm "$h2/.inputrc"; ln -s "$REPO/home/.inputrc" "$h2/.inputrc"              # (d) absolute link
rm -r "$h2/.config/mise"; printf 'x\n' >"$h2/.config/mise"                 # (e) file where a dir goes
before=$(snapshot "$h2")
out=$(install_into "$h2" 2>&1)
refute "install refuses and exits non-zero" install_quietly "$h2"
assert "a refused install changes nothing at all" same "$before" "$(snapshot "$h2")"
assert "names the Atuin file"                 grep_out '.config/atuin/config.toml' "$out"
assert "names the directory"                  grep_out '.ripgreprc' "$out"
assert "names the foreign symlink"            grep_out '.gitconfig' "$out"
assert "names the absolute symlink"           grep_out '.inputrc' "$out"
assert "names the file blocking a directory"  grep_out '.config/mise' "$out"
assert "says what to do about it"             grep_out '\-\-takeover' "$out"

group "Dry run"
before=$(snapshot "$h2")
assert "dry run with --takeover exits 0" install_into "$h2" --dry-run --takeover -q
assert "dry run changes nothing" same "$before" "$(snapshot "$h2")"

group "Takeover"
assert "takeover exits 0" install_into "$h2" --takeover -q
assert "the atuin config is linked again"        [ -L "$h2/.config/atuin/config.toml" ]
assert "the directory was replaced by a link"    [ -L "$h2/.ripgreprc" ]
assert "the foreign symlink was replaced"        [ -L "$h2/.gitconfig" ]
assert "the absolute symlink was replaced"       relative_link "$h2/.inputrc"
assert "the blocked directory exists again"      real_dir "$h2/.config/mise"
backup=$(find "$h2/.dotfiles-backup" -mindepth 1 -maxdepth 1 -type d | head -1)
assert "the Atuin file is in the backup, path preserved" [ -f "$backup/.config/atuin/config.toml" ]
assert "with its contents intact" grep -q 'generated by atuin' "$backup/.config/atuin/config.toml"
assert "the directory was backed up whole"  [ -f "$backup/.ripgreprc/junk" ]
assert "the foreign symlink was backed up"  [ -L "$backup/.gitconfig" ]
assert "exactly the five conflicting paths were backed up, nothing else" entry_count "$backup" 5
before=$(snapshot "$h2")
install_into "$h2" -q
assert "post-takeover rerun is still a no-op" same "$before" "$(snapshot "$h2")"

group "A tree the old installer folded into the repository"
h3=$(newhome)
stow --dir "$REPO" --target "$h3" --dotfiles atuin home   # stow's default: folding
assert "setup: ~/.config is a fold into the repo" [ -L "$h3/.config" ]
assert "install over a folded tree exits 0" install_into "$h3" -q
assert "the fold was unfolded into a real directory" real_dir "$h3/.config"
assert "repository content was not moved out of the repo" [ -f "$REPO/atuin/.config/atuin/config.toml" ]
refute "nothing was backed up: none of it was a real conflict" [ -d "$h3/.dotfiles-backup" ]

group "Subsets and bad input"
h4=$(newhome)
assert "installing a subset exits 0" install_into "$h4" -q fish git starship
refute "packages outside the subset are left alone" [ -e "$h4/.vimrc" ]
refute "an unknown package is an error" install_quietly "$h4" nosuchpackage
refute "asking for a macOS package on Linux is refused" install_linux "$h4" hammerspoon

group "No duplicated lines, ever"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../lib/common.sh
. "$REPO/lib/common.sh"
h5=$(newhome)
append_line_once "$h5/f" "a line" || true
append_line_once "$h5/f" "a line" || true
append_line_once "$h5/f" "a line" || true
assert "append_line_once is idempotent" [ "$(grep -c 'a line' "$h5/f")" = 1 ]

group "shellcheck"
if command -v shellcheck >/dev/null 2>&1; then
  assert "every script is shellcheck-clean" shellcheck_all
else
  printf '  skip shellcheck is not installed\n'
fi

printf '\n%s passed, %s failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
