# remap prefix from 'C-b' to 'C-a'
# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix

# new windows and splits inherit current pane's working directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# increase scrollback buffer
set-option -g history-limit 5000

# enable modified key reporting (fixes Enter/other extended keys)
set -g extended-keys on

# makes pi happy
set -g extended-keys-format csi-u

# enable mouse support (allows clicking to select panes, resize, etc.)
set -g mouse on

# use fish as default shell
set-option -g default-shell /opt/homebrew/bin/fish

# don't rename windows automatically
set-option -g allow-rename off
set -g pane-border-format "#{pane_index} #{pane_title}"
set -g pane-border-status top
